### PR TITLE
added App class

### PR DESCRIPTION
**Pull request by medelhamdi**
Hi,
I have committed App please Review and approve

### CODE REVIEW

**Comment by meedhamdi** [comment]
Hi, med,
Your code looks good, please can you add getMessage() method in the try-catch block
Regards.

**Comment by medelhamdi** [comment]
ok sir thanks for the review

**Comment by medelhamdi** [comment]
Hi,
I have added the getMessage method please Review and approve

**Comment by meedhamdi** [comment]
ok, med,
the code looks good now go ahead and merge the branch with master branch

**Pull request merged**
